USE master
GO

IF DB_ID('BD_RESTAURANT') IS NOT NULL
BEGIN
	DROP DATABASE BD_RESTAURANT
END
GO

--CREAMOS LA BASE DE DATOS
CREATE DATABASE BD_RESTAURANT
GO
--UTILIZAMOS LA BASE DE DATOS
USE BD_RESTAURANT
GO
--COMANDO PARA DARLE FORMATO A LA FECHA DE NUESTRA BASE DE DATO
SET DATEFORMAT dmy
go

--TABLA SALON
CREATE TABLE SALON(
Id_Salon			INT IDENTITY PRIMARY  KEY NOT NULL
,Salon				VARCHAR(50) NOT NULL
--,Usuario_Creacion	VARCHAR(30)
--,Pc_Creacion		VARCHAR(30)
--,Fecha_Creacion		DATETIME
,Estado				CHAR(1) DEFAULT '1'
,CHECK (Estado IN('0','1'))
)
GO

--TABLA MESA
CREATE TABLE MESA(
Id_mesa					INT IDENTITY PRIMARY  KEY NOT NULL
,mesa					VARCHAR(50) NOT NULL
,salon_id				INT NOT NULL
,estado_de_vida			CHAR(1) DEFAULT '1'
,estado_disponibilidad	CHAR(1) DEFAULT '1'
,CHECK (estado_de_vida IN('0','1'))
,CHECK (estado_disponibilidad IN('0','1'))
,CONSTRAINT FK_SALON_MESA FOREIGN KEY(Salon_Id) REFERENCES SALON(Id_Salon)
)
GO
